### ISSUE TITLE
systemd service won't start sonarr

### ISSUE THREAD

**Issue by chrisjohnson00** [lifeofguenter/ansible-role-sonarr#1]
```
vagrant@vagrant:~$ sudo service sonarr status
● sonarr.service - sonarr
   Loaded: loaded (/lib/systemd/system/sonarr.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2017-06-27 20:36:20 UTC; 17ms ago
  Process: 17669 ExecStart=/usr/bin/mono /opt/NzbDrone/NzbDrone.exe -nobrowser (code=exited, status=217/USER)
 Main PID: 17669 (code=exited, status=217/USER)

Jun 27 20:36:20 vagrant systemd[1]: sonarr.service: Service hold-off time over, scheduling restart.
Jun 27 20:36:20 vagrant systemd[1]: Stopped sonarr.
Jun 27 20:36:20 vagrant systemd[1]: sonarr.service: Start request repeated too quickly.
Jun 27 20:36:20 vagrant systemd[1]: Failed to start sonarr.
```

This is on an empty ubuntu 1604 server after running the ansible role with nothing else.
Running sonaar manually via `mono --debug /opt/NzbDrone/NzbDrone.exe` works fine.

**Comment by lifeofguenter** [comment]
Are you running it manually with the same user as `sonarr_user` ?

**Comment by chrisjohnson00** [comment]
I was running it as the `vagrant` user.  I just destroyed and re-upped my vagrant and when I run the service commands (first thing I do on the machine after provisioning) I get a different error.  I think based on the error that mono isn't being installed by this role?  I'll look into this more later/tomorrow and put in a PR if there's something that I think needs to be fixed.

```
vagrant@vagrant:~$ sudo service sonarr status
● sonarr.service - sonarr
   Loaded: loaded (/lib/systemd/system/sonarr.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
vagrant@vagrant:~$ sudo service sonarr start
vagrant@vagrant:~$ sudo service sonarr status
● sonarr.service - sonarr
   Loaded: loaded (/lib/systemd/system/sonarr.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Jun 27 21:56:00 vagrant systemd[1]: Stopped sonarr.
Jun 27 21:56:00 vagrant systemd[1]: Started sonarr.
Jun 27 21:56:00 vagrant systemd[19763]: sonarr.service: Failed at step USER spawning /usr/bin/mono: No such process
Jun 27 21:56:00 vagrant systemd[1]: sonarr.service: Main process exited, code=exited, status=217/USER
Jun 27 21:56:00 vagrant systemd[1]: sonarr.service: Unit entered failed state.
Jun 27 21:56:00 vagrant systemd[1]: sonarr.service: Failed with result 'exit-code'.
Jun 27 21:56:00 vagrant systemd[1]: sonarr.service: Service hold-off time over, scheduling restart.
Jun 27 21:56:00 vagrant systemd[1]: Stopped sonarr.
Jun 27 21:56:00 vagrant systemd[1]: sonarr.service: Start request repeated too quickly.
Jun 27 21:56:00 vagrant systemd[1]: Failed to start sonarr.
```

**Comment by chrisjohnson00** [comment]
looking at the ansible tasks more, the `sonaar_user` isn't created by the task, but is expected to exist in the startup service.  I'll put in a PR with a user create task added to the install.  Is that acceptable?  Or should I put in a PR for the documentation stating that the user must pre-exist?

**Comment by lifeofguenter** [comment]
Ah oops you are right. The reason why I am not yet confident in automatically creating `sonarr_user` is that "traditionally" users might have a specific user that runs a bunch of "media" services (like nzbget, samba, etc.) thus avoiding complications with filesystem permissions - e.g. in that case creating the user as part of this role might get to complex as there would be quite some additional config options.

So I think for now I should just document it better "please make sure `sonarr_user` already exists - is part of your playbook setup" or so.

**Comment by chrisjohnson00** [comment]
i think it would be pretty benign to add the [user creation](http://docs.ansible.com/ansible/user_module.html), it only creates if it isn't already there.  either way is groovy man!
